global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka_jmx'
    static_configs:
      - targets: ['jmx-exporter:5556']

  - job_name: 'kafka_exporter'
    static_configs:
      - targets: ['kafka_exporter:9308']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
