apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: MySQL
    type: mysql
    access: proxy
    url: localhost:3306
    database: microservices
    user: root
    password: 
    jsonData:
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
      timeInterval: "1m"
    editable: true

  